# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#permalink:         notes/:categories/:title/
permalink:         notes/:title/
#relative_permalinks: true

# Setup
title:            Jon Bartlett
tagline:          '' 
description:      'My personal website'
url:              http://www.jonbartlett.org
baseurl:          ''

author:
  name:           'Jon Bartlett'
  url:            https://twitter.com/MrJonBartlett

# paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jonbartlett/jonbartlett.github.io

gems:
  - jekyll-sitemap
